-- Exploratory Data Analysis (EDA)
-- Explore all objects in the database
-- Database Exploration

SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all columnds in the database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


-- Dimensions Exploration
-- Explore All countries our customers come from.

SELECT DISTINCT country
FROM gold.dim_customers

-- Explore all categories "the major divisions"

SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
ORDER BY 1,2,3

-- Date Exploration
-- Find the date of the first and last order

SELECT MIN(order_date) First_Order_Date, 
MAX(order_date) Last_Order_Date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) AS order_range_years
from gold.fact_sales

-- Find the youngest and oldest customer

SELECT
MIN(birthdate) AS Oldest_birtdate,
DATEDIFF(year,MIN(birthdate),GETDATE()),
DATEDIFF(year,max(birthdate),GETDATE()),
MAX(birthdate) AS Youngest_birtdate
FROM gold.dim_customers

-- Measures Exploration 

-- Find the Total Sales
SELECT SUM(sales_amount) AS Total_Amount FROM gold.fact_sales
-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales
-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales
-- Find the Total number of Orders
SELECT COUNT(order_number) AS Total_number FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS Total_number FROM gold.fact_sales
-- Find the total number of products
SELECT COUNT(product_key) AS Total_products  FROM gold.dim_products
SELECT COUNT(DISTINCT product_key) AS Total_products FROM gold.dim_products
-- Find the total number of customers
SELECT COUNT(DISTINCT customer_key) AS Total_customer FROM gold.dim_customers
-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales

-- Generate a report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS Total_Amount FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name,SUM(quantity) AS total_quantity FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name,AVG(price) AS avg_price FROM gold.fact_sales
UNION ALL
SELECT 'Total nr. Orders' AS measure_name,COUNT(DISTINCT order_number) AS Total_number FROM gold.fact_sales
UNION ALL
SELECT 'Total nr. Products' AS measure_name,COUNT(DISTINCT product_key) AS Total_products FROM gold.dim_products
UNION ALL
SELECT 'Total nr. Customers' AS measure_name,COUNT(DISTINCT customer_key) AS Total_customer FROM gold.dim_customers


-- Magnitude 

-- Find total customers by countries
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;
-- Find total customers by gender
SELECT gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;
-- Find total products by category
SELECT category,
COUNT(product_key) AS total_customers
FROM gold.dim_products 
GROUP BY category
ORDER BY total_customers DESC;
-- What is the average costs in each category?
SELECT category, 
AVG(cost) AS Avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_cost DESC;
-- What is the total revenue generated for each category?
SELECT 
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY Total_revenue DESC;
-- Find total revenue is generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;
-- What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(f.quantity) AS total_sold_item
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_item DESC;

-- Ranking Top N - Bottom N
-- Ranking analysis

-- Which 5 products generate the highest revenue?
SELECT 
top 5 c.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products c
ON f.product_key = c.product_key
GROUP BY c.product_name
ORDER BY total_revenue DESC;
-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC


-- ALTERNATIVE WINDOW FUNCTION 
SELECT * -- YOU CAN CALL THIS SUBQUERY
FROM (
SELECT
p.product_name,
SUM(f.sales_amount) AS total_revenue,
ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
)t
WHERE rank_products <= 5

-- Find the top-10 customers who have generated the highest revenue 
-- and 3 customers with the fewest orders placed

SELECT *
FROM (
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS Total_revenue,
ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_customers
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name)t
WHERE rank_customers <= 10;

SELECT 
top 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS Total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY Total_orders
